[tool.poetry]
name = "manim-course-utils"
version = "0.1.0"
description = "Para el curso de ManimCE de MathLike"
authors = ["MathLike <benjamin.ubilla@uc.cl>"]
readme = "README.md"
packages = [{include = "manim_course_utils"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
manim = "^0.17.3"


[[tool.poetry.source]]
name = "GitHub"
url = "https://github.com/MathLike/manim-course-utils"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
